version: "3.8"

services:
  app:
    container_name: backend-template-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "sleep infinity"
    restart: unless-stopped
    user: node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
